Layer5 welcome logo changed to Meshery logos with dark and light them…
meshery/meshkit pull request #308
Opened 2023-05-01 11:10 UTC by om2137

**Description**
Replace the Logo of Layer5 with Meshery in the config.yml workflow

This PR fixes #296 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-05-08 12:09 UTC, thisiskaransgit commented on .github/config.yml
>    Thanks for your contribution to the Layer5 community! :tada:
```suggestion
  Thanks for your contribution to Meshery! :tada:
```

2023-05-09 22:24 UTC, leecalcote requested changes
@anshgoyalevil, please assist @om2137 by correcting the instructions offered in the corresponding issue.

2023-05-10 01:53 UTC, anshgoyalevil commented on .github/config.yml
> +  </picture>
Thanks for the changes @om2137 🛩️ 

There are some changes required.

- The ```srcset``` needs to be a reference to absolute path to raw image.
- The name of the images needs to be more clear, as explained by @thisiskaransgit 
- Also, I think, you have interchanged the white image to dark color scheme, and black to light color scheme.

Please refer to the following example

```
Thanks for your contribution to Meshery! :tada:
   
  <picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://raw.githubusercontent.com/meshery/meshery/master/.github/assets/images/Meshery-celebration-Dark.svg">
  <source media="(prefers-color-scheme: light)" srcset="https://raw.githubusercontent.com/meshery/meshery/master/.github/assets/images/Meshery-celebration-Light.svg">
  <img alt="Meshery Logo" src="">
  </picture>
```

Or, Following Merged PR, referring to a similar issue - https://github.com/meshery/meshery/pull/7586/files

2023-05-27 09:53 UTC, goldfishdolphin commented
@om2137 are you still working on the issue?

2023-06-21 04:43 UTC, anshgoyalevil commented
@om2137 Are you still working on the issue? Feel free to ping me here or on slack if you are facing any issues.

2023-06-22 12:47 UTC, om2137 commented
> @om2137 Are you still working on the issue? Feel free to ping me here or on slack if you are facing any issues.

Hey extremely sorry, I didn't get the notification for this.
but I thought some one already fixed this issue in other pr.

If you want you can take this

2023-06-22 12:48 UTC, anshgoyalevil commented
@om2137 Alright 😅 Would you like to close this PR?

2023-07-11 16:09 UTC, merged