[Policy] add rego policy support in meshkit
meshery/meshkit pull request #311
Opened 2023-05-09 22:04 UTC by Abhishek-kumar09

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-05-09 22:13 UTC, leecalcote commented
@acald-creator no issues with dependencies here, right?

2023-05-09 22:13 UTC, leecalcote requested changes

2023-05-09 22:13 UTC, leecalcote commented on models/meshmodel/core/policies/data_models.go
@MUzairS15 @theBeginner86 will you help ensure that this struct is built from schema?

2023-05-09 22:14 UTC, leecalcote commented
Is this struct being defined in MeshKit so that the same struct can be used in Meshery Cloud or for another reason?

2023-05-09 23:25 UTC, acald-creator commented
reviewing

2023-05-10 13:32 UTC, leecalcote commented on models/meshmodel/core/policies/data_models.go
@Abhishek-kumar09 is it?

2023-05-10 13:44 UTC, Abhishek-kumar09 commented on models/meshmodel/core/policies/data_models.go
No. Its a response structure we would like to enforce. It contains the mix of information required for the javascript(frontend) and some about the port settings.

the `port` given it is `map[string]inerface{}` comes directly from what you provide in the design-file, thus following the schema rules.

2023-05-10 13:46 UTC, Abhishek-kumar09 commented on models/meshmodel/core/policies/data_models.go
currently it is unused, the server would be the one to unmarshall the response from policy engine to this struct.

2023-05-10 13:49 UTC, Abhishek-kumar09 commented
> Is this struct not being defined in Meshery Server, but in MeshKit so that the same struct can be used in Meshery Cloud or for another reason?

https://github.com/meshery/meshery/pull/7654#discussion_r1188501841
Since the policy engine is described here in the meshkit, its corresponding struct is also written here. But, it is meant to be used by the server, or any other client that could intake policy and expect some data-response from it.

2023-05-10 19:21 UTC, Abhishek-kumar09 commented on models/meshmodel/core/policies/data_models.go
Since now I get your questions after the development call, @MUzairS15 or @theBeginner86 if you guys have some design-spec or some research work already in place, lets get to it.

2023-05-13 19:32 UTC, merged