K8 Unit tests
meshery/meshkit pull request #319
Opened 2023-05-20 20:13 UTC by Philip-21

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.
 
#### All unit tests for  k8 packages in Meshkit
K8 unit tests for describe package continuation from pr #306 and #287

2023-05-28 04:59 UTC, Aisuko commented
> @Revolyssup pls I will need the Pr to be reviewed, I feel I am really missing something in the code to make the test case work . As you had said earlier, i created and initialized a test.yml file to be used as my meshclient. When running the testcase it gave this error message , “A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.”
> 
> @Aisuko mentioned using a controller-runtime to create a response. I'll need your review on this to continue working with the Pr

Yes, we have done this in `meshery-operator` as you mentioned above. For `meshery/mshkit`. It would be better if we can get some suggestions from @Revolyssup. As I mentioned before, please get a confirmation of the solution, after that it is good to go.

2023-05-28 05:00 UTC, Aisuko requested changes
Please check the CI issues

2023-06-04 17:58 UTC, Philip-21 commented
> Please check the CI issues

i have checked the ci issues it has to do with the response errors i mentioned  earlier, i have pinged @Revolyssup  i am still waiting for his reply and suggestions

2023-06-12 06:03 UTC, Revolyssup requested changes

2023-06-12 06:03 UTC, Revolyssup commented on utils/kubernetes/describe/describe_test.go
> +		RequestUrl:   fmt.Sprintf("%sapi/v1/namespaces", ctx),
@Philip-21 You dont need to use `ctx` here as the prefix. Use the address given in test.yml

2023-09-11 01:31 UTC, Aisuko commented
Hi, @Philip-21 Are you still working on it?

2023-09-20 19:56 UTC, Philip-21 commented
> Hi, @Philip-21 Are you still working on it?

Yes, i will create time and look into this

2023-11-15 21:45 UTC, closed without merging