Register components based on ui compatibility
meshery/meshkit pull request #327
Opened 2023-07-14 11:49 UTC by MUzairS15

**Description**
Every component has `uiCompatible` property in their `metadata`. If `uiCompatible` property is unset then the component is still registered (if schema is valid) but not returned to UI.
`uiCompatible ` can be un-set in 2 cases:
1. Schema is not present,
2. UI cannot handle the schema correctly (eg: CRD).
**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-07-14 20:35 UTC, leecalcote requested changes
Where is the proposal for this new attribute `uiCompatible`?

2023-07-14 20:37 UTC, MUzairS15 commented
> Where is the proposal for this new attribute `uiCompatible`?

Discussed here. https://app.clickup.com/t/85ztfxqh4?comment=90020034409921

2023-08-02 17:58 UTC, leecalcote commented
@MUzairS15 has this been separately addressed as `isAnnotation`?

2023-08-02 18:02 UTC, leecalcote commented
Close this PR?

2023-08-02 18:03 UTC, MUzairS15 commented
No, this is different this was more about exposing control to user to selectively enable / disable meshmodels

2023-08-02 18:04 UTC, closed without merging