update fields to retrieve HostID and name
meshery/meshkit pull request #332
Opened 2023-07-22 21:17 UTC by Freedisch

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.
 Update fields for Models, Relationships, and components to display host Id and name

2023-07-23 13:37 UTC, leecalcote commented
@zakisk

2023-07-23 16:48 UTC, zakisk requested changes
@Freedisch code in terms of solving issue is good but linting must be added

2023-07-23 16:48 UTC, zakisk commented on models/meshmodel/core/v1alpha1/models.go
> +	HostID	    uuid.UUID			   `json:"hostID"`
@Freedisch please add linting at the moment you can see that stylistically code isn't good.

2023-07-23 18:03 UTC, zakisk approved these changes

2023-07-25 04:56 UTC, MUzairS15 requested changes
@Freedisch Have you verified your changes? Do you get `HostID, HostName, DisplayHostName` when you query for model? 
You also need to modify GetModel IMO.

2023-07-25 06:28 UTC, Freedisch commented
@MUzairS15 ,  I already modified GetModel it's in another PR in Meshery, 
here the body response
![image](https://github.com/meshery/meshkit/assets/82499435/36863bd2-d94a-4b9c-bf21-2918fc32996e)

2023-07-25 15:49 UTC, MUzairS15 commented
> @MUzairS15 , I already modified GetModel it's in another in this PR [#8257](https://github.com/meshery/meshery/pull/8257), here the body response ![image](https://user-images.githubusercontent.com/82499435/255808245-36863bd2-d94a-4b9c-bf21-2918fc32996e.png)
> 
> Regarding the model, are the available models registered under a host/or registrant? ![image](https://user-images.githubusercontent.com/82499435/255810208-52639cfe-3e3f-4087-8959-2b812a25bc27.png)

This is what I was referring to the second screenshot the hostname and id are empty, you need to modify [getmodels](https://github.com/meshery/meshkit/pull/331)

2023-08-02 10:54 UTC, Freedisch commented
@MUzairS15 
![image](https://github.com/meshery/meshkit/assets/82499435/683603e0-011f-4977-88bf-54f0d0765968)

2023-08-02 13:36 UTC, MUzairS15 requested changes
@Freedisch I understand that you are retrieving registrants and assigning host details (in your meshery PR), but host details are now included in Model constructs so why not set host details while retrieving models? https://github.com/meshery/meshkit/pull/332/files#diff-69b1a3b3507297713ffe3c635a25bbf8a8807b7a2c316a8bed048c222fde7b55R194

2023-08-02 17:57 UTC, leecalcote commented
merge conflict

2023-08-03 16:33 UTC, Freedisch commented
@MUzairS15, thoughts? i updated the pr

2023-08-09 22:03 UTC, leecalcote commented
Rady for re-review, @MUzairS15

2023-08-10 05:14 UTC, Freedisch commented
@leecalcote, sorry forgot to close this one. The changes here have been already merged here #337

2023-08-10 05:14 UTC, closed without merging