Move InvokeGenerator to a centralized function of Meshkit
meshery/meshkit pull request #543
Opened 2024-07-23 10:12 UTC by dusdjhyeon

**Description**

This PR fixes #541 

**Notes for Reviewers**
- I moved InvokeGenerator directly into the generators folder, rather than generators/models, due to **circular reference** issues. 
- The functions I moved to utils can now be made to import meshkit from meshery. 
- The terminal output for registry generate in meshery suggests using **io.MultiWriter**. 

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-07-24 14:13 UTC, MUzairS15 commented
@Jougan-0 @dusdjhyeon Is there any change in logic?

2024-07-24 14:33 UTC, Jougan-0 commented
> @Jougan-0 @dusdjhyeon Is there any change in logic?

Nope it was just basic migration.
Next on her list is to update the logs on terminal to show the Models that are being generated in real time and if the program is waiting for an Artifacthub rate limit then show the log of Generation paused for x amount of time for Artifacthub registrant.

2024-07-29 09:40 UTC, dusdjhyeon commented
> @dusdjhyeon Did you run this locally? I mean do you have google sheets configured?

I copied meshery Google sheets in my google account and invited my gcp api email and used it.

2024-07-29 09:41 UTC, Jougan-0 commented
> > @dusdjhyeon Did you run this locally? I mean do you have google sheets configured?
> 
> I copied meshery Google sheets in my google account and invited my gcp api email and used it.

Was everything working fine and models were generated?

2024-07-29 13:21 UTC, dusdjhyeon commented
> > > @dusdjhyeon Did you run this locally? I mean do you have google sheets configured?
> > 
> > 
> > I copied meshery Google sheets in my google account and invited my gcp api email and used it.
> 
> Was everything working fine and models were generated?

Yes, I checked. 
![image](https://github.com/user-attachments/assets/0efb55a1-a9ab-4636-baad-e989d520a9dd)

2024-07-29 13:21 UTC, Jougan-0 commented
Reviewed on Meshery PR to remove logrus please do so and let's get this merged.

2024-07-29 23:23 UTC, leecalcote commented
> Reviewed on Meshery PR to remove logrus please do so and let's get this merged.

👍

2024-07-30 15:03 UTC, MUzairS15 requested changes

2024-07-30 15:03 UTC, MUzairS15 commented on utils/registry/error.go
> +func ErrFileRead(err error) error {
Error already exists, please re-use/enhance.

2024-07-30 15:03 UTC, MUzairS15 commented on utils/registry/error.go
> +func ErrCreateDir(err error, obj string) error {
Error already exists, please re-use/enhance.

2024-07-30 15:03 UTC, MUzairS15 commented on utils/registry/error.go
> +	ErrAppendToSheetCode      = "mesheryctl-1116"
Update the error code, please. It's meshkit.

To reduce manual work, replace the code with empty string and run meshkit error utility.

2024-07-30 15:03 UTC, MUzairS15 commented on utils/registry/error.go
> +func ErrGenerateComponent(err error, modelName, compName string) error {
Check once, this should also exist.

2024-09-28 04:25 UTC, closed without merging