Fix #575: Replaced deprecated utils.Unmarshal and removed unused variables
meshery/meshkit pull request #579
Opened 2024-08-25 16:55 UTC by ShivanshuGupta07

**Description**

This PR fixes #575 by replacing deprecated `utils.Unmarshal` with `json.Unmarshal` and removing unused variables from the codebase.

**Notes for Reviewers**

- The changes involve updates to two specific files: `config/provider/inmem.go` and `utils/kubernetes/crd.go`.
- Please verify that the replacement of `utils.Unmarshal` does not impact any other parts of the code that may rely on its specific behavior.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**

- [x] Yes, I signed my commits.

2024-09-17 05:14 UTC, leecalcote commented
Thank you, @ShivanshuGupta07!

2024-09-19 10:19 UTC, MUzairS15 commented
@ShivanshuGupta07 merge conflicts

2024-09-23 00:50 UTC, lekaf974 requested changes
Please fix comments + lint error

2024-09-23 00:50 UTC, lekaf974 commented on config/provider/inmem.go
> +	//return utils.Unmarshal(l.store[key], result)
Con you remove this since it is no more used

2024-09-23 00:50 UTC, lekaf974 commented on utils/kubernetes/crd.go
> +	//err = utils.Unmarshal(string(crdresult), &xcrd)
same

2024-09-26 13:51 UTC, MUzairS15 requested changes
I don't this PR is required.

2024-09-26 13:51 UTC, MUzairS15 commented on utils/kubernetes/crd.go
> -	err = encoding.Unmarshal(crdresult, &xcrd)
`encoding.Unmarshal` is not deprecated, in fact recommended to be used. 
It is the encoder recently added in Meshkit, which supports both `json/yaml`.

2024-09-26 13:51 UTC, MUzairS15 commented on config/provider/inmem.go
> -	return encoding.Unmarshal([]byte(l.store[key]), result)
same here

2024-09-27 15:47 UTC, ShivanshuGupta07 commented
@MUzairS15, so no changes are request now?

2025-01-09 23:01 UTC, closed without merging